### PR TITLE
 Done!

### PR DESCRIPTION
**Pull request by Gortaur**

### CODE REVIEW

**Comment by pigovsky** [comment]
why have you removed `readme` file?

**Comment by Gortaur** [comment]
Because i forgot about him.

**Comment by pigovsky** [comment]
readd it, please using command
```
git checkout HEAD~  README.md
```

**Comment by pigovsky** [comment]
why do your source files have *.txt extension?

**Comment by Gortaur** [comment]
Why not?

**Comment by pigovsky** [comment]
will a c# compiler (for instance csc.exe) compile these source files with txt extensions?

**Comment by Gortaur** [comment]
I dont think so.

2016-09-26 17:41 GMT+03:00 pigovsky <notifications@github.com>:

**Comment by pigovsky** [comment]
so rename the files!

**Comment by Gortaur** [comment]
Okay(

**Comment by pigovsky** [comment]
rename them and commit and push your changes

**Comment by Gortaur** [comment]
Ok

**Comment by pigovsky** [comment]
I have asked you to RENAME the files, why have you removed them?

**Comment by Gortaur** [comment]
Ready!

**Pull request merged**
